import './bootstrap';
import 'ol';
//require('@ol');
// import Feature from './ol/Feature.js';
// import Geolocation from './ol/Geolocation.js';
// import Map from './ol/Map.js';
// import Point from './ol/geom/Point.js';
// import View from './ol/View.js';
// import {Circle as CircleStyle, Fill, Stroke, Style} from './ol/style.js';
// import {OSM, Vector as VectorSource} from './ol/source.js';
// import {Tile as TileLayer, Vector as VectorLayer} from './ol/layer.js';
// import {fromLonLat} from './ol/proj';
